"""change some model in

Revision ID: 5a9a7df16e7a
Revises: af4265d782de
Create Date: 2025-02-02 17:50:31.598019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9a7df16e7a'
down_revision: Union[str, None] = 'af4265d782de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teachers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teachers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teachers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teachers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teachers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
