"""Ad new tables

Revision ID: 9854f4afb63a
Revises: 2208f758cd4d
Create Date: 2025-02-04 15:02:59.934626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9854f4afb63a'
down_revision: Union[str, None] = '2208f758cd4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('imgae', sa.String(), nullable=True),
    sa.Column('A', sa.String(), nullable=False),
    sa.Column('B', sa.String(), nullable=False),
    sa.Column('C', sa.String(), nullable=False),
    sa.Column('D', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('quiz_result', sa.JSON(), nullable=True))
    op.add_column('students', sa.Column('corect_result', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('incorrect_result', sa.Integer(), nullable=True))
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('students', 'incorrect_result')
    op.drop_column('students', 'corect_result')
    op.drop_column('students', 'quiz_result')
    op.drop_table('questions')
    # ### end Alembic commands ###
