"""Delete forting

Revision ID: a947e689ae57
Revises: 79c7b8c94246
Create Date: 2025-02-03 16:11:07.236046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a947e689ae57'
down_revision: Union[str, None] = '79c7b8c94246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
